# Stage 1: Build React App
FROM node:18-alpine AS builder
WORKDIR /app
# Copy dependencies files (use Docker cache)
COPY package.json package-lock.json* ./
# Clean install dependencies
RUN npm ci
# Copy the rest of the code and build
COPY . .
RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginxinc/nginx-unprivileged:alpine
# Copy the custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf
# Copy the static files from the build stage
COPY --chown=nginx:nginx --from=builder /app/dist /usr/share/nginx/html
# Use non-root user for security
USER nginx
# Expose the port that Nginx will use
EXPOSE 8080
# Command to start Nginx
CMD ["nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]